version: "3.7"

services:
  crmapp:
    build: .
    depends_on:
      - postgresdb
#    image: 214964386210.dkr.ecr.eu-west-2.amazonaws.com/crmapp:1.0
    ports:
      - 8088:8088
    volumes:
      - ./crm_api/src/:/usr/src/app/
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: maroussiaarnault
      POSTGRES_PASSWORD: 9*rCNK94#pij
      POSTGRES_DB: crmapp
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5440:5432
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
#  crm_api:
#    container_name: crm_api
#    hostname: crm_api
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 54322:5000
#    volumes:
#      - ./crm_api/src/:/usr/src/app/
#      - /usr/src/app/node_modules # Don't need these
#    restart: unless-stopped
#    depends_on:
#      - postgres
#  # The webserver will hold the source code for our website (via volumes).
#  # Also notice that we map 2 ports in this container: 80 and 443 (http and https).
#  crm_webserver:
#    container_name: crm_webserver
#    hostname: crm_webserver
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./crm_webserver/src/test:/usr/share/nginx/html
#    restart: always
#    depends_on:
#      - postgres
volumes:
  postgres:
  pgadmin:
