# Workflow build with Github Actions: Release Changelog Builder (https://github.com/marketplace/actions/release-changelog-builder#configuration-specification)
name: 'Changelog and Github Release'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    tags:
      - '*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v0.1.14 #softprops/action-gh-release
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            Release.txt
            LICENSE
