name: 'Changelog and Github Release'
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Which tag do we want to release on?'
        required: true
        type: string

  pull_request:
    branches:
      - master
    tags:
      - '*'

jobs:
  gh-release:
    #if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Generate Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: build/*.zip


      # - name: Create Github Release
      #   uses: softprops/action-gh-release@v0.1.14 #softprops/action-gh-release
      #   with:
      #     body: ${{ steps.build_changelog.outputs.changelog }}
